#!/usr/bin/env python3
"""
validate_ats_companies.py — Keep only ATS board tokens that are live and hiring.

Probes every candidate token against Greenhouse, Lever and Ashby public job-board
APIs and writes data/ats_companies.yaml with the tokens that return 200 and at
least one job.

Usage:
  python scripts/validate_ats_companies.py              # re-validate data/ats_companies.yaml
  python scripts/validate_ats_companies.py --probe      # also probe data/ats_candidates.txt
                                                        # tokens on all three ATSs
"""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import requests
import yaml

ROOT = Path(__file__).parent.parent
OUT_PATH = ROOT / "data" / "ats_companies.yaml"
CANDIDATES_PATH = ROOT / "data" / "ats_candidates.txt"
UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) hermes-job-search/1.0"}

ENDPOINTS = {
    "greenhouse": "https://boards-api.greenhouse.io/v1/boards/{t}/jobs",
    "lever": "https://api.lever.co/v0/postings/{t}?mode=json",
    "ashby": "https://api.ashbyhq.com/posting-api/job-board/{t}",
}


def job_count(ats: str, token: str) -> int:
    """Number of open postings on the board; 0 when the board is missing or unreachable."""
    try:
        resp = requests.get(ENDPOINTS[ats].format(t=token), headers=UA, timeout=15)
    except requests.RequestException as exc:
        print(f"  [validate] {ats}/{token}: network error {exc.__class__.__name__}")
        return 0
    if resp.status_code != 200:
        return 0
    try:
        data = resp.json()
    except ValueError:
        return 0
    if ats == "lever":
        return len(data) if isinstance(data, list) else 0
    return len(data.get("jobs", [])) if isinstance(data, dict) else 0


def load_pairs(probe: bool) -> set[tuple[str, str]]:
    pairs: set[tuple[str, str]] = set()
    if OUT_PATH.exists():
        existing = yaml.safe_load(OUT_PATH.read_text()) or {}
        for ats, tokens in existing.items():
            pairs |= {(ats, t) for t in tokens or []}
    if probe and CANDIDATES_PATH.exists():
        for line in CANDIDATES_PATH.read_text().splitlines():
            token = line.split("#")[0].strip().lower()
            if token:
                pairs |= {(ats, token) for ats in ENDPOINTS}
    return pairs


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--probe", action="store_true", help="probe data/ats_candidates.txt too")
    args = parser.parse_args()

    pairs = sorted(load_pairs(args.probe))
    print(f"[validate] probing {len(pairs)} (ats, token) pairs...")
    with ThreadPoolExecutor(max_workers=16) as pool:
        counts = list(pool.map(lambda p: job_count(*p), pairs))

    valid: dict[str, list[str]] = {ats: [] for ats in ENDPOINTS}
    for (ats, token), n in zip(pairs, counts):
        if n > 0:
            valid[ats].append(token)
    for ats in valid:
        valid[ats] = sorted(set(valid[ats]))

    OUT_PATH.parent.mkdir(exist_ok=True)
    header = "# Generated by scripts/validate_ats_companies.py — live boards with >=1 open job.\n"
    OUT_PATH.write_text(header + yaml.safe_dump(valid, sort_keys=True))
    total = sum(len(v) for v in valid.values())
    summary = ", ".join(f"{a}={len(v)}" for a, v in valid.items())
    print(f"[validate] {total} live boards ({summary}) -> {OUT_PATH}")


if __name__ == "__main__":
    main()
